---
title: "GP_About"
author: "Yuanxi Cheng"
date: "2022-08-19"
output: html_document
---

## About the Project

#### Originating in the grassy mildew hills of Scotland's eastern coast, the sport of golf arose over 500 years ago when a group of Scottish people played a gamne of hitting pebbles across hills with curved wooden sticks. In the mid 1700s, the first official rules of golf as what resembles the rules it plays by today were made. The sport quickly gained popularity in Scotland, and in no time it had been a sport played by many, from peasants to royal families. Around that same time, golf had entered the New World in the colonies. Fast forward to the 21st century, the sport of golf has become widely popular in America, and many of the greatest players are competing in world-renowned tournaments held in the US, such as the US Open and the Masters. But as golf continues to be a prominent sport within the US, the future of golf comes into question. Golf has become a great sport led by legends like Tiger Woods, but where will the sport go under the leadership of the rising generation of junior golfers? And so, the purpose of this project is evaluate the popularity, performance, and potential growth of golf through analysis of competitive junior golfer information.

#### All of information, data-processing, graphs, and the R Shiny website itself are created via code in the R language through R Studio.

## The Goals We Aim For

#### Working with Professor Zhaoxia Yu as part of the UCI Summer Research Program, the underlying goal of our project is to utilize and perform statistic analysis through the through computer coding programs. Because statistics and data science have a large field of application, we chose to focus on an analysis of golf, which may seem a little unorthodox in a program calling for scientific research. However, this project is just as scientific, as it is the process of statistical analysis itself that reflects its scientific nature. However, analyzing datasets containing thousands of values manually proves to be a little impossible, so the use of R, a computer coding language, has been crucial to this project. Under the tutelage of Professor Yu, this project has been a process of computer-driven statistical analysis datasets involving golf, such as player populations and available golf courses by state, as well as datasets that have possible relations and effects on golf popularity, such as weather and household income, in order to evaluate what drives the popularity of golf to thrive, and to get a more visual sense of golf demographics in the US. 

#### Our final result is to able to analyze and determine which factors have a significant impact on the popularity of golf, be it state population, weather, or Median Income. 

## Literary Review

#### Before picking the goal of our project, research on other golf research was done, and there were a lot of research papers involving technologies to make better clubs or to create more distance, as well as many data sets of PGA Tour players and their statistics. I found that it would be interesting to be involved in a study that took a step back from the intricacies of golf playing performance, and instad focus the popularity and distribution of golf as a whole. 

#### An organization that I've found to be incredibly similar to the intentions of this study is the National Golf Foundation, NGF, which focuses on using factors of golf popularity to create demographics of golf, so that golf companies and organizations looking to open new stores or golf courses have an idea of where to go. While NGF is a large foundation with a large of employees, I am a single person who is learning how to code R while creating this project, so I cannot make anything close to the magnitude of what NGF has to offer. So while this project is similar to what the NGF offers, it focuses less of finding the areas where golf may be most popular and more of the different possible predictors and their significance of impact on golf popularity.

#### Navigation - each of the options along the top bar will take you to more detailed evaluations of different factors and includes attempts of fitting linear models



