---
title: "GP_Visualization"
author: "Yuanxi Cheng"
date: "2022-08-19"
output: html_document
---

### Visualized Data

```{r, echo=FALSE}
library(usmap)
library(ggplot2)
library(shiny)
library(knitr)

boys <- read.csv("C:/Users/roy19/OneDrive/Documents/JGSBoys.csv", head= T)
girls <- read.csv("C:/Users/roy19/OneDrive/Documents/JGSGirls.csv", head=T)
State_Pop <- read.csv("C:/Users/roy19/OneDrive/Documents/State_Population.csv", head = T)
State_Income <- read.csv("C:/Users/roy19/OneDrive/Documents/State_Med_Income.csv", head = T)
State_Courses <- read.csv("C:/Users/roy19/OneDrive/Documents/State_Courses.csv", head = T)
State_Weather <- read.csv("C:/Users/roy19/OneDrive/Documents/State_Weather.csv", head = T)
```

```{r, echo=FALSE}
#Processing data for JGS boys
#unique(boys$Ctry)

boysUS <- boys[(boys$Ctry=="US"),]
boysUS$St.Prov <- toupper(boysUS$St.Prov)
boysUS <- boysUS[!((boysUS$St.Prov=="--"|boysUS$St.Prov=="BC"|boysUS$St.Prov=="AB"|boysUS$St.Prov=="GU"|boysUS$St.Prov=="DC"|boysUS$St.Prov=="PR")),]
boysUS <- subset(boysUS, select = -c(1,2,7,9,10,11,12,13))
rownames(boysUS) <- 1:nrow(boysUS)

#boysUS
#unique(boysUS$Ctry)
#unique(boysUS$St.Prov)
#nrow(boysUS)
#nrow(boys)
#head(boysUS,10)

#Processing JGS Girls
girlsUS <- girls[(girls$Ctry=="US"),]
girlsUS$St.Prov <- toupper(girlsUS$St.Prov)
girlsUS <- girlsUS[!((girlsUS$St.Prov=="--"|girlsUS$St.Prov=="BC"|girlsUS$St.Prov=="AB"|girlsUS$St.Prov=="GU"|girlsUS$St.Prov=="DC"|girlsUS$St.Prov=="PR")),]
girlsUS <- subset(girlsUS, select = -c(1,2,7,9,10,11,12,13))
rownames(girlsUS) <- 1:nrow(girlsUS)

#head(girlsUS, 10)
#unique(girlsUS$Ctry)
#unique(girlsUS$St.Prov)
#nrow(girlsUS)
#nrow(girls)
```

```{r, echo=FALSE}
#boys US map
boys_map <- data.frame(state = unique(boysUS$St.Prov))
boys_map[nrow(boys_map) + 1,] <- c("AK")
Bpopulation <- c()
for (i in boys_map$state) {
  temp_count = 0
  for (k in boysUS$St.Prov) {
    if (i == k) {
      temp_count = temp_count + 1
    }
  }
  Bpopulation <- c(Bpopulation, temp_count)
}
#Bpopulation
boys_map$pop <- Bpopulation
boys_map <- boys_map[order(boys_map$state),]
rownames(boys_map) <- 1:nrow(boys_map)
#head(boys_map, 10)

p1<- plot_usmap(regions = "states", data = boys_map, values = "pop", color = "black")+
   scale_fill_continuous(low = "white", high = "red", name = "Population Num", label = scales::comma)+
   labs(title = "JGS Boys in US", subtitle = "Population of Competitive Junior Golf Boys across the US") +
   theme(legend.position = "right")

#girls US map
girls_map <- data.frame(state = unique(girlsUS$St.Prov))
girls_map[nrow(girls_map) + 1,] <- c("SD")
girls_map[nrow(girls_map) + 1,] <- c("AK")
girls_map[nrow(girls_map) + 1,] <- c("VT")
girls_map[nrow(girls_map) + 1,] <- c("ME")
Gpopulation <- c()
for (i in girls_map$state) {
  temp_count1 = 0
  for (k in girlsUS$St.Prov) {
    if (i == k) {
      temp_count1 = temp_count1 + 1
    }
  }
  Gpopulation <- c(Gpopulation, temp_count1)
}
girls_map$pop <- Gpopulation
girls_map <- girls_map[order(girls_map$state),]
rownames(girls_map) <- 1:nrow(girls_map)
#head(girls_map, 10)

p2<- plot_usmap(regions = "states", data = girls_map, values = "pop", color = "black")+
   scale_fill_continuous(low = "white", high = "red", name = "Population Num", label = scales::comma)+
   labs(title = "JGS Girls in US", subtitle = "Population of Competitive Junior Golf Girls across the US") +
   theme(legend.position = "right")

#Combined Map 
boys_temp <- boys_map
girls_temp <- girls_map
for (i in 1:50) {
  boys_temp$pop[i] <- boys_temp$pop[i]+girls_temp$pop[i] 
}
junior_map <- boys_temp
p3<- plot_usmap(regions = "states", data = junior_map, values = "pop", color = "black")+
   scale_fill_continuous(low = "white", high = "red", name = "Population Num", label = scales::comma)+
   labs(title = "JGS Players in US", subtitle = "Population of Competitive Junior Players Across the US") +
   theme(legend.position = "right")
print(p1)
print(p2)
print(p3)
```

```{r, echo=FALSE}
#Boys With standardized population
State_Pop_Temp <- State_Pop[-c(1:5),]
State_Pop_Temp$NAME <- state.abb[match(State_Pop_Temp$NAME,state.name)]
State_Pop_Temp <- State_Pop_Temp[order(State_Pop_Temp$NAME),]
rownames(State_Pop_Temp) <- 1:nrow(State_Pop_Temp)
pop_stand_boys <- boys_map
for (i in 1:50) {
  pop_stand_boys$pop[i] <- pop_stand_boys$pop[i]/State_Pop_Temp$POPESTIMATE2021[i]
}
p4<- plot_usmap(regions = "states", data = pop_stand_boys, values = "pop", color = "black")+
  scale_fill_continuous(low = "white", high = "red", name = "Population Num", label = scales::comma)+
  labs(title = "JGS Boys in US With Standardized Population", subtitle = "Population of Competitive Junior Golf Boys across the US, 
       standardized by estimate population of people in each state.") +
  theme(legend.position = "right")

#Girls With Standardized Population
pop_stand_girls <- girls_map
for (i in 1:50) {
  pop_stand_girls$pop[i] <- pop_stand_girls$pop[i]/State_Pop_Temp$POPESTIMATE2021[i]
}
p5<- plot_usmap(regions = "states", data = pop_stand_girls, values = "pop", color = "black")+
  scale_fill_continuous(low = "white", high = "red", name = "Population Num", label = scales::comma)+
  labs(title = "JGS Girls in US With Standardized Population", subtitle = "Population of Competitive Junior Golf Girls across the US,
       standardized by estimate population of people in each state.") +
  theme(legend.position = "right")

#Combined With Standardized Population
pop_stand_junior <- junior_map
for (i in 1:50) {
  pop_stand_junior$pop[i] <- pop_stand_junior$pop[i]/State_Pop_Temp$POPESTIMATE2021[i]
}
p6<- plot_usmap(regions = "states", data = pop_stand_junior, values = "pop", color = "black")+
  scale_fill_continuous(low = "white", high = "red", name = "Population Num", label = scales::comma)+
  labs(title = "JGS Players in US With Standardized Population", subtitle = "Population of Competitive Junior Golf Players across the US, 
       standardized by estimate population of people in each state.") +
  theme(legend.position = "right")
print(p4)
print(p5)
print(p6)
```

```{r, echo=FALSE}
  # Quick conversion of State_Courses' state names using State_Income
State_Income <- State_Income[order(State_Income$State),]
State_Courses["State"] <- State_Income["State"]


#Map of Median Household Income by State
#head(State_Income,5)
State_Income$State <- state.abb[match(State_Income$State,state.name)]
State_Income <- State_Income[order(State_Income$State),]
rownames(State_Income) <- 1:nrow(State_Income)
colnames(State_Income)[1] <- "state"

p7<-plot_usmap(regions = "states", data = State_Income, values = "HouseholdIncome", color = "black")+
  scale_fill_continuous(low = "white", high = "red", name = "Income Amount", label = scales::comma)+
  labs(title = "Median Household Income", subtitle = "Census of the median reported household income per state") +
  theme(legend.position = "right")

  #Total Players divided household income
pop_per_income <- junior_map
pop_per_income$pop <- pop_per_income$pop/State_Income$HouseholdIncome

p8<-plot_usmap(regions = "states", data = pop_per_income, values = "pop", color = "black")+
  scale_fill_continuous(low = "white", high = "red", name = "Income Amount", label = scales::comma)+
  labs(title = "Players Per Median Household Income", subtitle = "Players in each state standardized by median income") +
  theme(legend.position = "right")
print(p7)
print(p8)
```

```{r, echo=FALSE, warning=FALSE}
#Map of golf courses in each state
#head(State_Courses, 5)
State_Courses$State <- state.abb[match(State_Courses$State,state.name)]
colnames(State_Courses)[1] <- "state"
colnames(State_Courses)[2] <- "Courses"
State_Courses$Courses <- as.numeric(State_Courses$Courses)
State_Courses[is.na(State_Courses)] = 1044
p9<-plot_usmap(regions = "states", data = State_Courses, values = "Courses", color = "black")+
  scale_fill_continuous(low = "white", high = "red", name = "Golf Courses", label = scales::comma)+
  labs(title = "Golf Courses By State", subtitle = "Number of established golf courses across each state") +
  theme(legend.position = "right")


#Map of players per golf courses in each state
pop_per_course <- junior_map
for (i in 1:50) {
  pop_per_course$pop[i] <- pop_per_course$pop[i]/State_Courses$Courses[i]
}
p10<-plot_usmap(regions = "states", data = pop_per_course, values = "pop", color = "black")+
  scale_fill_continuous(low = "white", high = "red", name = "Population Num", label = scales::comma)+
  labs(title = "JGS Players in US in Relation to Courses", subtitle = "Population of Competitive Junior Golf Players across the US 
       divided by the total number of golf courses in each state") +
  theme(legend.position = "right")
print(p9)
print(p10)
```

```{r, echo=FALSE}
#For girls only
pop_per_course_girls <- girls_map
for (i in 1:50) {
  pop_per_course_girls$pop[i] <- pop_per_course_girls$pop[i]/State_Courses$Courses[i]
}
p11<- plot_usmap(regions = "states", data = pop_per_course_girls, values = "pop", color = "black")+
  scale_fill_continuous(low = "white", high = "red", name = "Population Num", label = scales::comma)+
  labs(title = "JGS Girls in US in Relation to Courses", subtitle = "Population of Competitive Junior Golf Girls across the US 
       divided by the total number of golf courses in each state") +
  theme(legend.position = "right")

  #For Boys only
pop_per_course_boys <- boys_map
for (i in 1:50) {
  pop_per_course_boys$pop[i] <- pop_per_course_boys$pop[i]/State_Courses$Courses[i]
}

p12<-plot_usmap(regions = "states", data = pop_per_course_boys, values = "pop", color = "black")+
  scale_fill_continuous(low = "white", high = "red", name = "Population Num", label = scales::comma)+
  labs(title = "JGS Boys in US in Relation to Courses", subtitle = "Population of Competitive Junior Golf Boys across the US 
       divided by the total number of golf courses in each state") +
  theme(legend.position = "right")
print(p11)
print(p12)
```

```{r, echo= FALSE}
#Map of girls to all juniors ratio
gbtotal_ratio <- girls_map
gbtotal_ratio$pop <- gbtotal_ratio$pop/junior_map$pop
p13<-plot_usmap(regions = "states", data = gbtotal_ratio, values = "pop", color = "black")+
  scale_fill_continuous(low = "white", high = "red", name = "Population Num", label = scales::comma)+
  labs(title = "Girl to Boy Ratio Per State", subtitle = "ratio of Junior Girls to Boys in each state") +
  theme(legend.position = "right")
print(p13)
```

```{r, echo=FALSE}
#Map of Avg Weather
State_Weather$state <- state.abb[match(State_Weather$state,state.name)]
p14<-plot_usmap(regions = "states", data = State_Weather, values = "AvgF", color = "black")+
  scale_fill_continuous(low = "white", high = "red", name = "Temp", label = scales::comma)+
  labs(title = "Avg Temp by State", subtitle = "The annual average temperature from 1971-2000 of each state by Fahrenheit") +
  theme(legend.position = "right")

  #Map of Precipitation
p15<-plot_usmap(regions = "states", data = State_Weather, values = "mm", color = "black")+
  scale_fill_continuous(low = "white", high = "red", name = "mm", label = scales::comma)+
  labs(title = "Avg Precipitation by State", subtitle = "The annual precipitation from 1971-2000 of each state by millimeters") +
  theme(legend.position = "right")

  #Map of Percent Humidity
p16<-plot_usmap(regions = "states", data = State_Weather, values = "Afternoon", color = "black")+
  scale_fill_continuous(low = "white", high = "red", name = "Percent", label = scales::comma)+
  labs(title = "Annual Avg Relative Humidity by State", subtitle = "The annual percent humidity of each state from 1971-2000") +
  theme(legend.position = "right")
print(p14)
print(p15)
print(p16)
```


